---
kind: pipeline
type: docker
name: docs

steps:
  - name: npm_auth
    image: robertstettner/drone-npm-auth
    settings:
      path: ./theme/
      token:
        from_secret: npm_token

  - name: build
    image: committed/ci:1.2.0
    commands:
      - yarn install
      - yarn clean
      - yarn build

  - name: deploy
    image: committed/ci:1.2.0
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - ./ci-config.sh -u "${DRONE_COMMIT_AUTHOR_NAME}" -e "${DRONE_COMMIT_AUTHOR_EMAIL}"
      - yarn deploy
    when:
      ref:
        - refs/tags/v*

  - name: code-analysis
    image: committed/drone-sonarqube-node
    environment:
      SONAR_HOST:
        from_secret: sonar_host
      SONAR_TOKEN:
        from_secret: sonar_token
    settings:
      exclusions: "**/node_modules/**/*,**/dist/**/*.js"
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

  - name: slack
    image: plugins/slack
    settings:
      channel: group-ci
      webhook:
        from_secret: slack_webhook
      template:
        from_secret: slack_template
    when:
      status:
        - failure

  - name: announce
    image: plugins/slack
    settings:
      channel: group-dev
      webhook:
        from_secret: slack_webhook
      template: >
        :tada: New version ${DRONE_TAG} of `@committed/docs` available, http://committed.software/docs
    when:
      ref:
        - refs/tags/v*
      status:
        - success
